config/routes.rb
Rails.application.routes.draw do
  root 'pages#show'
  get "/pages/:pages" => "pages#show"
  get 'signup' => 'users#new'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy'
  resources :users 
  resources :events 
  resources :invites, only: [:new, :create]

  resources :sessions
  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, :class_name => "User"
  has_many :invites, :foreign_key => "attended_event_id"
  has_many :attendees, :through => :invites
  scope :past, -> { where("date < ?", Date.today)}
  scope :upcoming, -> { where("date >= ?", Date.today )}
  validates :title, presence: true
  validates :date, presence: true
  validates :body, presence: true
  
  
 
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :attendee, :class_name => "User"
  belongs_to :attended_event, :class_name => "Event"
  
  validates :attendee, presence: true
  validates :attended_event, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :events, :foreign_key => "creator_id"
has_many :invites, :foreign_key => "attendee_id"
has_many :attended_events, :through => :invites

validates :name, presence: true
validates :email, presence: true




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include UsersHelper
  include EventsHelper
  
  end
  

app/controllers/events_controller.rb
class EventsController < ApplicationController
def new
   @event = current_user.events.new
end
def create
  @event = current_user.events.build(events_params)
  if @event.save
    @invite = current_user.invites.build({:attended_event_id => @event.id, :attendee_id => @event.creator.id})
    @invite.save
    redirect_to @event
  else
    render 'new'
  end
    
end 

def show
  @attendees = Event.find(params[:id]).attendees
  @event = Event.find(params[:id])
  @invite = Invite.create
  
end

def index 
  @past_events = Event.past
  @upcoming_events = Event.upcoming
  
end

private
  def events_params
    params.require(:event).permit(:title, :date,  :body)
  end
  
  def invite_params
    params.require(:invite).permit(:attendee_id, :attended_event_id)
  end
  
  
  def current_user
      current_user = User.find(session[:user_id])
    end


end

app/controllers/invite_controller.rb
class InviteController < ApplicationController
  def new
  end
  
  def create
    @invite = Invite.new(params)
    @invite.save
  end
  
  
  
  private
  

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def new
  end
  
  def create
    @invite = Invite.new(invite_params)
    @invite.save
    @user = User.find(session[:user_id])
    redirect_to @user
    
  end
  
  
  
  private
  
  def invite_params
    params.permit(:attendee_id, :attended_event_id)
  end
  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def show
  render template: "pages/home.html.erb"
end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    end
  
  def create
    user = User.find_by("name = ?", session_params[:name])
    
    if !user.nil?
      login user
      redirect_to root_path
    else
     redirect_to signup_path
    end
  end
  
  def destroy
    reset_session
    redirect_to :root
  end
  

  private
  
  def session_params
    params.require(:session).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include ApplicationHelper
before_action :require_login, only: [:index]
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      flash[:success] = "Welcome to Private Events"
      redirect_to '/users'
    else
      render 'new'
    end
  end
  
  def show
    @events = User.find(params[:id]).events
    upcoming_events
    past_events
    
    end
    
  def index
    @users = User.all
  end
    
    
    
   
  
  private
    def user_params
    params.require(:user).permit(:name, :email)
  end
  
    def current_user
      current_user = User.find(session[:user_id])
    end
    
    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this area"
        redirect_to signup_path
      end
    end
      
end

app/helpers/application_helper.rb
module ApplicationHelper

  def login(user)
    session[:user_id] = user.id
  end 
  
  def logged_in?
    !session[:user_id].nil?
  end
  
  def current_user
    User.find(session[:user_id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  
  
    
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def login(user)
    session[:user_id] = user.id
  end  
  
  def find_user
    @user = User.find_by("name = ?", params[:name])
    login(@user)
  end

  def upcoming_events
    user = User.find(params[:id])
    @upcoming_events = user.attended_events.where("date >= ?", Date.today)
  end
  
  def past_events
    user = User.find(params[:id])
    @past_events = user.attended_events.where("date < ?", Date.today)
  end
    
end

app/views/events/_event.html.erb
<%= @events.each do |event| %>
<li>
  <%= event.title %>
  <%= event.body %>
</li>

<% end %>

app/views/events/_events.html.erb
<%= @events.each do |event| %>
<li>
  <%= event.title %>
  <%= event.body %>
</li>

<% end %>

app/views/events/index.html.erb
<div class = "col col-md-5" >
  <div class = "container" >
  <h1>Future Events</h1>

    <div class = "event" >
      <ul>
      <% @upcoming_events.each do |event| %>
        <li>
        <%= link_to event.title, Event.find(event.id) %></li>
          <ul><li><%= event.date %></li>
              <li><%= event.body %></li>
              <li><%= link_to "Go to Event Page", event_path(event.id) %></li>
          </ul>
        </li>
      <% end %>
      </ul>
    </div>
  <h1>Past Events</h1>
    <div class= "event" >
    
      <ul>
      <% @past_events.each do |event| %>
      <li>
      <%= link_to event.title, Event.find(event.id) %><br>
        <ul><li><%= event.date %></li>
            <li><%= event.body %></li>
        </ul>
      </li>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div>
<%= form_for(@event) do |f| %>

  
  <%= f.label "Date" %>
  <%= f.date_field(:date) %>
  
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  
  <%= f.label "Description" %>
  <%= f.text_area :body %>
  
  <%= f.submit "Submit"%>
<% end %>
</div>

app/views/events/show.html.erb
<div class = " col-md-5" >
<div class = "container" >
<div class = "event" >
<h1><%= @event.title %> </h1>
<h4><%= @event.body %> </h4>
<p>Event created by <%= @event.creator.name %>
 </p><% unless @attendees.each.nil? %>
<p>Attending the event:</p>
<ul>
<% @attendees.each do |person| %>
  <li><%= link_to person.name, User.find(person.id)  %></li>
<% end %>
<% end %>
</ul>

<p>Event id : <%= @event.id %></p>
<p>Current Users id is : <%= session[:user_id] %></p>

<% if logged_in? %>
<%= button_to "Attend", {controller: "invites", action: "create", :attendee_id=> session[:user_id], :attended_event_id=> @event.id}, :method=>:post  %>
<% else %>
<%= button_to "Sign in to attend this event", signup_path, method: :get, class:"btn btn-primary btn-medium" %>
<% end %>


</div>
</div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Private Events", :root, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
        <% if logged_in? %>
          <%= link_to User.find(session[:user_id]).name, current_user %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "All Events", events_path %></li>
          <li><%= link_to "New Event", new_event_path %></li>
          <li><%= link_to "Log out", logout_path %></li>
        <% else %>
          <li><%= link_to "About", "#" %></li>
          <li><%= link_to "Sign up", signup_path %></li>
          
        <% end %>
                
     
        
        
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class = "container text-center">
<div class = "jumbotron">
<h1>Welcome</h1>
<div class="row-md-5">
  <p>Create your own events and manage the invitations with this sample app for TheOdinProject.com</p>
  <h2>Create an account to get started planning today!</h2>

  
  <%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-sm" %>
  
  
  
  </div>
    


</div>
</div>

app/views/session/new.html.erb
<h1> Log into for Private Events </h1>
<div>
<%= form_for (:session) do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.submit "Log into my account" %>
  <% end %>

</div>

  

app/views/users/find_user.html.erb
<h1> Sign up for Private Events </h1>
<div>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.email_field :name %>

  
  <%= f.submit "Sign into my account" %>
  <% end %>
</div>

app/views/users/index.html.erb
<h2> All Users </h2>
<div class = "col-md-4">
<div class = "container">
<ul class="list-group col-md-4">
<% @users.each do |f|%>
  <li class="list-group-item"><%=link_to f.name, User.find(f.id) %>     <%= f.email %></li>
  
<% end %>
</div>
</div>


  

app/views/users/login.html.erb
<h1> Sign up for Private Events </h1>
<div>
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  
  <%= f.submit "Sign into my account" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class = "col" >
<div class = "container" >


<h1> Sign up for Private Events </h1>
<div>
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.submit "Create my account" %>
  <% end %>  <div class="row text-center">
  <p>Already a user?</p>
  <%= link_to "Sign in", login_path, class: "btn btn-md btn-primary" %>
</div>

</div>

</div>
</div>


  

app/views/users/show.html.erb
<h1><%= User.find(params[:id]).name %>'s Page</h1>
<h2> Upcoming Events </h2>
<ul class = "list-group">
<% @upcoming_events.each do |event| %>
  <li class = "list-group-item"><h4><%= event.title %></h4>
  <p><%= event.body %></p>
  <p>hosted by : <%=link_to event.creator.name, User.find(event.creator.id) %>
  <p> happening on <%= event.date %></p></li>
<% end %></ul>
<h2>Past Events</h2>
<ul>
<% @past_events.each do |past| %>
  <li><%= past.title %></li>
  <%= past.body %>
  <%= past.date %>
<% end %></ul>
  
  